export const RANDOMIZER_OPTIONS = [
  {
    displayText: "Games",
    options: [
      "Sims",
      "Animal Crossing",
      "Mario Party",
      "Mario Kart",
      "Borderlands 3",
      "COD Duty",
      "Tricky Towers",
      "Monopoly",
      "Spongebob Battle for Bikini Bottom",
      "Stardew Valley",
      "Overcooked",
    ],
  },
  {
    displayText: "Casual Restaurants",
    options: [
      "Chipotle",
      "Chipotle",
      "Chipotle",
      "Subway",
      "Subway",
      "Chick-Fil-A",
      "Culvers",
      "DQ Grill & Chill",
      "Panera",
      "Applebees",
      "Applebees",
      "Wahlburgers",
      "Red Cow",
      "Shake Shack",
      "Perkins",
      "Perkins",
      "Leeann Chin",
      "Panda Express",
      "Canes",
      "Buffalo Wild Wings",
      "Dominos",
      "Dominos",
      "Olive Garden",
      "Jersey Mikes",
      "TGI Fridays",
      "5-8 Grill",
      "50s Grill",
      "Muddy Cow",
      "Wheelhouse",
      "Hudys Cafe",
      "China Hope",
      "Noodles & Company",
      "The Wienery",
    ],
  },
  {
    displayText: "Fancy Restaurants",
    options: [
      "Crave",
      "The Local",
      "Cheesecake Factory",
      "Nolos",
      "Freehouse",
      "Brick and Bourbon",
      "Biaggis",
      "PF Changs",
      "Buona Sera",
      "Osaka",
    ],
  },
  {
    displayText: "Adventures",
    options: [
      "Minneapolis Institute of Art",
      "Bell Museum",
      "Alamo Drafthouse",
      "Science Museum",
      "Walker Art Museum",
      "Sculpture Garden",
      "Sports Game",
      "Color Me Happy",
      "Live Music",
      "Play",
      "Acme Comedy Club",
      "Mall",
      "Night Drive",
      "Night Drive",
      "History Museum",
      "Find Something Fun To Do (Online)",
      "Rent out Apartment Theater",
      "Casino",
      "Minnesota Zoo",
      "Como Zoo",
      "Can Can Wonderland",
      "Bunkers Live Music",
      "Dave & Busters",
      "Updown",
      "Updown",
    ],
  },
];
