export const RANDOMIZER_OPTIONS = [
    {
      displayText: "Games",
      options: [
        "Sims",
        "Animal Crossing",
        "Mario Party",
        "Mario Kart",
        "Borderlands 3",
        "COD Duty",
        "Tricky Towers",
        "Monopoly",
        "Spongebob Battle for Bikini Bottom",
        "Stardew Valley",
      ],
    },
    {
      displayText: "Casual Restaurants",
      options: [
        "Chipotle",
        'Chipotle',
        'Chipotle',
        "Subway",
        "Chick-Fil-A",
        "Chick-Fil-A",
        "Culvers",
        "Erberts and Gerberts",
        "Burger King",
        "DQ Grill & Chill",
        "Panera",
        "Applebees",
        "Wahlburgers",
        "Red Cow",
        "Shake Shack",
        "Perkins",
        "Leeann Chin",
        "Panda Express",
        "Canes",
        "Buffalo Wild Wings",
        "Dominos",
      ],
    },
    {
      displayText: "Fancy Restaurants",
      options: [
        "Crave",
        "The Local",
        "Cheesecake Factory",
        "Nolos",
        "Freehouse",
        "Brick and Bourbon",
        "Biaggis",
        "PF Changs",
        "Buona Sera",
      ],
    },
  ];